
# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script and requirements.txt into the container at /app
COPY vpn-client.py .
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set up logging directory
RUN mkdir -p /app/logs

# Run the Python script when the container launches
CMD ["python", "./vpn-client.py"]


