# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
# RUN apt-get update \
#     && apt-get install -y --no-install-recommends net-tools \
#     && rm -rf /var/lib/apt/lists/*
# Install system dependencies
# RUN apt-get update \
#     && apt-get install -y --no-install-recommends net-tools wireguard \
#     && rm -rf /var/lib/apt/lists/*

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        net-tools wireguard \
        docker.io \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set up logging directory
RUN mkdir -p /app/logs

# Create the directory for WireGuard configuration
RUN mkdir -p /opt/homebrew/etc/wireguard
# Set permissions for the directory
RUN chmod 700 /opt/homebrew/etc/wireguard

# Copy application code
COPY . .

# Copy .env file to Docker image
COPY .env .env

# Expose the API port
EXPOSE 8001

# Command to run the application
CMD ["uvicorn", "wirevpnserver:app", "--host", "0.0.0.0", "--port", "8001", "--log-level", "debug"]
